INSERT INTO "user"(code, login, phonenumber, roleid, password, email)
VALUES ('XXXX5', 'executor1', '+79998887701', 4, '1', 'ivanov.aa@yandex.ru'),
       ('XXXX6', 'executor2', '+79998888802', 4, '1', 'petrov.sergey@yandex.ru'),
       ('XXXX7', 'organizer2', '+79998887703', 4, '1', 'ostin@yandex.ru'),
       ('XXXX8', 'executor3', '+79998888804', 4, '1', 'dyatlov@yandex.ru');

INSERT INTO specification(name, roleid, description)
VALUES ('Аниматор',
        (SELECT id FROM role WHERE role.name = 'EXECUTOR'),
        'Занимается организацией конкурсов для детей'),
       ('Ассистент аниматора',
        (SELECT id FROM role WHERE role.name = 'EXECUTOR'),
        'Занимается помощью основному аниматору'),
       ('Водитель',
        (SELECT id FROM role WHERE role.name = 'EXECUTOR'),
        'Занимается перевозкой пассажиров'),
       ('Повар',
        (SELECT id FROM role WHERE role.name = 'EXECUTOR'),
        'Занимается приготовлением пищи'),
       ('Официант',
        (SELECT id FROM role WHERE role.name = 'EXECUTOR'),
        'Занимается подачей пищи к столу'),
       ('Аквагримёр',
        (SELECT id FROM role WHERE role.name = 'EXECUTOR'),
        'Занимается нанесением аквагрима'),
       ('DJ',
        (SELECT id FROM role WHERE role.name = 'EXECUTOR'),
        'Занимается звукорежиссёрскими заботами')
;

INSERT INTO userinfo(userid,
                     name,
                     contactphonenumber,
                     description,
                     country,
                     region,
                     city,
                     street,
                     house,
                     lat,
                     lon,
                     dateofbirth,
                     status)
VALUES ('5', 'Иванов Александр', '+79998887701',
        'Мастер на все руки...',
--         'Россия', 'Брянская область',
--         'Брянск', '3-Интернационала', '29',
--         53.303456, 34.300821,
        'Россия', 'Брянская область',
        'Выгоничи', 'Нижняя', '54',
        53.127269,34.092796,
        now(), 'Мастер!'),
       ('6', 'Петров Сергей', '+79998887702',
        'Отличный мастер на все руки',
--         'Россия', 'Брянская область',
--         'Брянск', 'Медведева', '56',
--         53.311873, 34.288509,
        'Россия', 'Брянская область',
        'Путевка', 'Зеленая', '3',
        53.259283, 34.298791,
        now(), 'Мастер x2!'),
       ('7', 'Остин Джеймс', '+79998887703',
        'Звукорежиссёр без особых навыков',
        'Россия', 'Брянская область',
        'Брянск', 'Флотская', '6',
        53.291131, 34.290896,
        now(), 'Живу музыкой'),
       ('8', 'Дятлов Денис', '+79998887704',
        'Похуже Остина',
        'Россия', 'Брянская область',
        'Брянск', 'Романа Брянского', '12',
        53.263526, 34.315952,
        now(), 'Всем добра')
;

INSERT INTO userinfospecification(userinfoid, specid)
VALUES
    (5, 5),
    (5, 6),
    (5, 7),
    (5, 9),
    (5, 11),
    (5, 10),
    (6, 5),
    (6, 6),
    (6, 7),
    (6, 9),
    (6, 10),
    (6, 11),
    (7, 6),
    (7, 8),
    (7, 9),
    (7, 11),
    (8, 5),
    (8, 6),
    (8, 9),
    (8, 11)
;