-- alter table calendar
-- add column specificationId bigint
-- references userinfospecification(specid);
--
-- alter table calendar
-- drop column userid;
--
-- alter table calendar
-- add column userInfoId bigint
--     references userinfospecification(userinfoid);